// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/node";
import rateLimiter from "./rate-limiter";

export default await createHonoServer({
  configure: (server) => {
    server.use(rateLimiter);
  },
});
