// generated by react-router-hono-server/dev
import { every, some } from "hono/combine";
import { createHonoServer } from "react-router-hono-server/node";
import { localNetwork } from "./local-network";
import { rateLimiter } from "./rate-limiter";

export default await createHonoServer({
  configure: (server) => {
    server.use(
      "/auth/*",
      some(localNetwork, every(rateLimiter({ minutes: 15, limit: 100 }))),
    );
  },
});
