name: Checkout Upstream
description: "Checkout upstream repo UNLESS we are in upstream itself"

inputs:
  pat_token:
    description: 'PAT token for checkout'
    required: true

runs:
  using: composite
  steps:
    - name: Check if upstream repo
      id: check_upstream
      shell: bash
      run: |
        REPO_URL=$(git config --get remote.origin.url)
        if [[ "$REPO_URL" == *"${{ env.UPSTREAM_REPOSITORY }}"* ]]; then
          echo "is_upstream=true" >> $GITHUB_OUTPUT
        else
          echo "is_upstream=false" >> $GITHUB_OUTPUT
        fi

    - name: Skip checkout
      if: steps.check_upstream.outputs.is_upstream == 'true'
      shell: bash
      run: echo "Skipping checkout because we are in upstream itself"

    - name: Checkout upstream repo
      if: steps.check_upstream.outputs.is_upstream == 'false'
      uses: actions/checkout@v4
      with:
        repository: ${{ env.UPSTREAM_REPOSITORY }}
        path: ${{ env.UPSTREAM_FOLDER }}
        token: ${{ inputs.pat_token }}

    - name: Move upstream repo
      if: steps.check_upstream.outputs.is_upstream == 'false'
      shell: bash
      run: mv ${{ env.UPSTREAM_FOLDER }} ${{ github.workspace }}/${{ env.UPSTREAM_FOLDER }}

    - name: List dit
      if: steps.check_upstream.outputs.is_upstream == 'false'
      shell: ls -al ${{ github.workspace }}