name: Setup Database
description: "Creates, syncs and seeds the SQLite database"

runs:
  using: composite
  steps:
    - name: 📥 Copy env file
      shell: bash
      run: cp .env.example .env

    - name: 📥 Create SQLite database file
      shell: bash
      run: touch prisma/data.db

    - name: 💃 Run Prisma database migration
      shell: bash
      run: npx prisma migrate dev

    - name: 💃 Run Snaplet sync
      shell: bash
      run: npx @snaplet/seed sync --config /home/runner/work/tzdb/tzdb/prisma/seed/seed.config.ts

    - name: 💃 Run Snaplet seed
      shell: bash
      run: npm run seed -- -- --force
